baseurl: "/Kadastrale-mutatieservices"
apiname: "StUF-koppelvlak Kadastrale mutatieservices"
versie-nr: "1.0.0"
restAPI-Alternatief: "Nee"
url: "http://localhost:4000"

# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld. 
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geöpend.
nav:
  - title: StUF-koppelvlak Kadastrale mutatieservices
    subnav:
      - title: Overzicht
        path: /
      - title: Aan de slag
        path: /Aan de slag 
      - title: ICT aanbod
        path: /ICT aanbod  
      - title: Techniek
        path: /Techniek
      - title: Opdrachtgeverschap
        path: /Opdrachtgeverschap  
      - title: Documentatie  
        path: /Documentatie
#      - title: Werkgroep  
#        path: /Werkgroep 

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: VNG-Realisatie/jekyll-theme-vng-realisatie

github: VNG-Realisatie/Kadastrale-mutatieservices

theme: jekyll-theme-time-machine

project_name: VNG-Realisatie/Kadastrale-mutatieservices

standard_family: StUF
